server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 301 /design/;
  }

  location /design/storybook/ {
    try_files $uri $uri/ /design/storybook/index.html;
  }

  location /design/ {
    try_files $uri $uri/ /design/index.html;
  }
}